Add JSON reader & extractor
CentreForDigitalHumanities/ianalyzer-readers pull request #27
Opened 2024-11-21 11:19 UTC by BeritJanssen

Close #6. This proved more complicated than I first envisioned, because the example data I found happened to be structured as arrays within a dictionary. This solution can now tackle both types of data: single file with multiple documents, or a file per document.

2024-12-02 13:25 UTC, lukavdplas commented
Apologies for the late response, I hadn't realised this was ready for review.

Before I review this, can you add relevant documentation changes in `/docs` and `README.md`? I would not have approved this without a documentation update, and it makes the rest of the review easier.

2024-12-19 12:15 UTC, BeritJanssen commented
@lukavdplas I included the json module in the mkdocs index, and updated the README to state that the package also defines a reader for JSON. I also just went ahead now and excluded the Python 3.8 test from the GitHub actions matrix, and edited the README to state that we don't support Python versions lower than 3.9.

2025-01-15 16:42 UTC, lukavdplas requested changes
Nice!

I have added two functional comments, about checking the class of the source and rejecting the JSON extractor in other readers. Please address those.

Other than that, I added some minor comments about clarity, and I'm not sure about adding pandas as a requirement, but those are not essential comments.

2025-01-15 17:11 UTC, BeritJanssen commented on pyproject.toml
> +  "pandas",
I actually struggled quite a bit with parsing a nested list next to flatter metadata, and the pandas implementation is far from trivial. I thought the "don't roll your own" policy applies here. I agree though that pandas is a heavy new dependency.

2025-01-16 11:26 UTC, lukavdplas commented on pyproject.toml
> +  "pandas",
Ah, I probably underestimated this at first glance. And you're right, it's a non-issue for I-analyzer. Let's go with the pandas solution then :+1:

2025-01-23 13:07 UTC, BeritJanssen commented on ianalyzer_readers/extract.py
> +        return data
That would be useful only in case we want to parse the whole contents of a file. I cannot imagine a use case for that on the top of my head. Leaving this for later.

2025-01-23 13:07 UTC, merged